/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VolunteersRouteImport } from './routes/volunteers'
import { Route as VolunteerAuthRouteImport } from './routes/volunteer-auth'
import { Route as ReportRouteImport } from './routes/report'
import { Route as MyReportsRouteImport } from './routes/my-reports'
import { Route as MapRouteImport } from './routes/map'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'

const VolunteersRoute = VolunteersRouteImport.update({
  id: '/volunteers',
  path: '/volunteers',
  getParentRoute: () => rootRouteImport,
} as any)
const VolunteerAuthRoute = VolunteerAuthRouteImport.update({
  id: '/volunteer-auth',
  path: '/volunteer-auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportRoute = ReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => rootRouteImport,
} as any)
const MyReportsRoute = MyReportsRouteImport.update({
  id: '/my-reports',
  path: '/my-reports',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/map': typeof MapRoute
  '/my-reports': typeof MyReportsRoute
  '/report': typeof ReportRoute
  '/volunteer-auth': typeof VolunteerAuthRoute
  '/volunteers': typeof VolunteersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/map': typeof MapRoute
  '/my-reports': typeof MyReportsRoute
  '/report': typeof ReportRoute
  '/volunteer-auth': typeof VolunteerAuthRoute
  '/volunteers': typeof VolunteersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/map': typeof MapRoute
  '/my-reports': typeof MyReportsRoute
  '/report': typeof ReportRoute
  '/volunteer-auth': typeof VolunteerAuthRoute
  '/volunteers': typeof VolunteersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/map'
    | '/my-reports'
    | '/report'
    | '/volunteer-auth'
    | '/volunteers'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/map'
    | '/my-reports'
    | '/report'
    | '/volunteer-auth'
    | '/volunteers'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/dashboard'
    | '/map'
    | '/my-reports'
    | '/report'
    | '/volunteer-auth'
    | '/volunteers'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRoute
  MapRoute: typeof MapRoute
  MyReportsRoute: typeof MyReportsRoute
  ReportRoute: typeof ReportRoute
  VolunteerAuthRoute: typeof VolunteerAuthRoute
  VolunteersRoute: typeof VolunteersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/volunteers': {
      id: '/volunteers'
      path: '/volunteers'
      fullPath: '/volunteers'
      preLoaderRoute: typeof VolunteersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/volunteer-auth': {
      id: '/volunteer-auth'
      path: '/volunteer-auth'
      fullPath: '/volunteer-auth'
      preLoaderRoute: typeof VolunteerAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report': {
      id: '/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof ReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-reports': {
      id: '/my-reports'
      path: '/my-reports'
      fullPath: '/my-reports'
      preLoaderRoute: typeof MyReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRoute,
  MapRoute: MapRoute,
  MyReportsRoute: MyReportsRoute,
  ReportRoute: ReportRoute,
  VolunteerAuthRoute: VolunteerAuthRoute,
  VolunteersRoute: VolunteersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
